version: '2'
services:
  ether:
    build: .
    command: python -u ether.py
    volumes:
      - .:/code
    links:
      - mongo
  litecoin:
    build: .
    command: python -u litecoin.py
    volumes:
      - .:/code
    links:
      - mongo
  ripple:
    build: .
    command: python -u ripple.py
    volumes:
      - .:/code
    links:
      - mongo
  nem:
    build: .
    command: python -u nem.py
    volumes:
      - .:/code
    links:
      - mongo
  bitcoin:
    build: .
    command: python -u bitcoin.py
    volumes:
      - .:/code
    links:
      - mongo
  dash:
    build: .
    command: python -u dash.py
    volumes:
      - .:/code
    links:
      - mongo
#  api:
#    build: .
#    command: python -u api.py
#    volumes:
#      - .:/code
#    links:
#      - mongo
#    ports:
#      - "5000:5000"
  mongo:
    image: 'mongo:3.4.1'
    volumes:
      - 'mongo:/data/db'
    ports:
    - "27017:27017"
    logging:
      driver: none
volumes:
  mongo:


